# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_location', models.CharField(max_length=100)),
                ('project_goal', models.BigIntegerField()),
                ('project_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_donations', models.BigIntegerField()),
                ('user_datejoined', models.DateTimeField()),
            ],
        ),
    ]
