# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_location', models.CharField(max_length=100)),
                ('project_goal', models.BigIntegerField()),
                ('project_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
