# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180301_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_Name',
        ),
    ]
