# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180301_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='project_Date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_goal',
            new_name='project_Goal',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_text',
            new_name='project_Info',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_location',
            new_name='project_Location',
        ),
    ]
