# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180301_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_Date',
            field=models.DateField(),
        ),
    ]
