# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180301_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_Name',
        ),
    ]
