# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_Name',
            field=models.CharField(default='Default Project Name', max_length=200),
            preserve_default=False,
        ),
    ]
