# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_Id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Id', models.IntegerField()),
                ('project_Id', models.IntegerField()),
                ('donation', models.IntegerField()),
            ],
        ),
    ]
