# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_donations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation',
            new_name='donated',
        ),
    ]
