# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180301_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_Reach',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
